/**
 * @file note.types.ts
 * @description Types for the Note entity — the atomic unit of Noteleaf.
 *
 * A Note is a classified, timestamped fragment of speech captured during a
 * recording session. The classifier assigns a NoteType based on language
 * patterns in the transcript segment.
 *
 * Notes are immutable after creation. Editing is not supported by design —
 * the app captures what was said, not what the user later thought was said.
 */

// ─── Classification ───────────────────────────────────────────────────────────

/**
 * Semantic classification of a captured speech segment.
 *
 * - `action`   → Something that needs to be done. Keywords: "we need to",
 *                "follow up", "can you", "by Friday", "assign".
 * - `decision` → A conclusion that was reached. Keywords: "decided",
 *                "agreed", "going with", "confirmed".
 * - `insight`  → An observation or idea worth remembering. Keywords:
 *                "important", "key point", "realized", "idea", "suggest".
 * - `summary`  → General statement that does not fit the above categories.
 *                This is the fallback type.
 */
export type NoteType = 'action' | 'decision' | 'insight' | 'summary';

// ─── Note entity ─────────────────────────────────────────────────────────────

/**
 * A single captured and classified note from a recording session.
 */
export interface Note {
  /** UUID v4. Generated by the client at capture time. */
  id: string;

  /** The session this note belongs to. Foreign key to Session.id. */
  sessionId: string;

  /** Semantic classification assigned by the note classifier. */
  type: NoteType;

  /**
   * The transcribed and lightly cleaned speech content.
   * First character is capitalised. No other post-processing.
   */
  content: string;

  /**
   * Keywords extracted from content for quick reference.
   * Max 3 tags per note. Stopwords excluded. Min word length: 5 chars.
   */
  tags: string[];

  /**
   * Wall-clock time when this speech segment was captured.
   * Displayed on the note card. ISO 8601 format.
   */
  capturedAt: string;

  /**
   * Seconds from session start when this note was captured.
   * Used to correlate notes with positions in the transcript.
   */
  sessionOffsetSeconds: number;

  /**
   * Set when the user manually edits the note content after capture.
   * Holds the original transcription so corrections can be used as
   * training signal to improve future speech recognition accuracy.
   */
  originalContent?: string;

  /**
   * True when the user has manually corrected this note's content or type.
   * Displayed as a small indicator on the card so it's clear what has
   * been reviewed vs. raw AI output.
   */
  isUserEdited?: boolean;
}

// ─── Classifier input/output ─────────────────────────────────────────────────

/**
 * Input to the note classifier — the raw finalized transcript segment
 * received from NVIDIA NIM's gRPC stream.
 */
export interface ClassifierInput {
  /** The finalized transcript text from NVIDIA NIM. Immutable after receipt. */
  transcript: string;

  /** The session this segment belongs to. */
  sessionId: string;

  /** Seconds elapsed in the current session when this segment completed. */
  sessionOffsetSeconds: number;
}

/**
 * Output of the note classifier — a fully formed Note ready for storage.
 */
export type ClassifierOutput = Note;
