/**
 * @file session.types.ts
 * @description Types for the Session entity.
 *
 * A Session is one continuous recording. It has a lifecycle:
 *   idle → recording → stopped → (optionally) summarised
 *
 * Sessions are the primary unit of cloud sync. When in cloud mode, each
 * session is persisted to the API keyed by userUuid. Sessions can be
 * retrieved by UUID from any device.
 *
 * In local mode, sessions live only in localStorage or the file system.
 */

import type { Note } from './note.types.js';

// ─── Session lifecycle ────────────────────────────────────────────────────────

/**
 * Represents the recording state of a session in the UI.
 * Used by the recording store to drive UI state changes.
 *
 * - `idle`       → No recording in progress. Mic button shows record icon.
 * - `recording`  → Actively capturing audio. Mic pulses red.
 * - `stopped`    → Recording ended. Notes are visible. AI button appears.
 * - `summarised` → AI summary has been generated and attached.
 */
export type SessionStatus = 'idle' | 'recording' | 'stopped' | 'summarised';

// ─── AI summary ───────────────────────────────────────────────────────────────

/**
 * Structured AI-generated summary of a session's notes and transcript.
 * Produced by NVIDIA NIM via the /api/ai/summarize endpoint.
 */
export interface AiSummary {
  /** UUID v4. Generated by the API at creation time. */
  id: string;

  /** The session this summary belongs to. */
  sessionId: string;

  /** One or two sentence overview of the meeting. */
  overview: string;

  /** Decisions that were reached during the session. */
  decisions: string[];

  /** Action items with optional owner attribution. */
  actionItems: string[];

  /** Notable ideas, insights, or discussion themes. */
  insights: string[];

  /**
   * The NVIDIA NIM model used to produce this summary.
   * Stored for auditing and reproducibility.
   * Example: 'nvidia/nemotron-3-super-120b-a12b'
   */
  modelUsed: string;

  /** ISO 8601 timestamp of when this summary was generated. */
  generatedAt: string;
}

// ─── Transcript ──────────────────────────────────────────────────────────────

/**
 * Verbatim transcript segment returned by the speech-to-text stream.
 * These are preserved separately from classified notes so users can review
 * what was said in chronological order with meeting-relative timestamps.
 */
export interface TranscriptSegment {
  /** UUID v4. Generated by the client when the final transcript arrives. */
  id: string;

  /** The session this transcript segment belongs to. */
  sessionId: string;

  /** Exact final transcript text returned by STT. */
  text: string;

  /** Wall-clock time when this final segment was received. */
  capturedAt: string;

  /** Seconds from session start when the segment began. */
  startOffsetSeconds: number;

  /** Seconds from session start when the segment ended. */
  endOffsetSeconds: number;

  /** STT confidence score, when provided. */
  confidence: number;
}

// ─── Session entity ───────────────────────────────────────────────────────────

/**
 * A complete recording session with all captured notes and optional summary.
 */
export interface Session {
  /** UUID v4. Generated by the client when the session is created. */
  id: string;

  /**
   * The UUID of the user who owns this session.
   * Used as the partition key for cloud storage.
   */
  userUuid: string;

  /**
   * User-provided session title. Optional — defaults to "untitled session".
   * Editable inline in the session header.
   */
  title: string;

  /** All notes captured during this session, in chronological order. */
  notes: Note[];

  /**
   * The full raw transcript of everything said during this session.
   * Concatenated from all NVIDIA NIM is_final=true results.
   * Stored for AI summarisation context. Not displayed in the UI.
   */
  transcript: string;

  /** Timestamped verbatim transcript segments in chronological order. */
  transcriptSegments: TranscriptSegment[];

  /** Total recording time in seconds. Set when the session is stopped. */
  durationSeconds: number;

  /**
   * AI-generated summary. Present only after the user explicitly requests it
   * via the "Generate smart notes" button.
   */
  aiSummary?: AiSummary;

  /**
   * Current lifecycle state. Stored with the session to restore UI
   * correctly when the user navigates back to a past session.
   */
  status: SessionStatus;

  /** ISO 8601 timestamp of when this session was first created. */
  createdAt: string;

  /** ISO 8601 timestamp of the most recent note, title change, or sync. */
  updatedAt: string;
}

// ─── Session list item ────────────────────────────────────────────────────────

/**
 * Lightweight projection used in the sidebar session list.
 * Avoids loading all notes and transcript just to render the list.
 */
export interface SessionListItem {
  id: string;
  userUuid: string;
  title: string;
  noteCount: number;
  durationSeconds: number;
  status: SessionStatus;
  hasAiSummary: boolean;
  /** True when loaded from cloud (i.e. not currently in localStorage). */
  isCloudOnly: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─── Session creation ─────────────────────────────────────────────────────────

/**
 * Payload used to initialise a new session on the client.
 * The API mirrors this shape when creating a new session record.
 */
export interface CreateSessionPayload {
  id: string;       // Pre-generated by the client (UUID v4)
  userUuid: string;
  title: string;
}

/**
 * Payload used to persist a session after recording stops.
 */
export interface UpdateSessionPayload {
  title?: string;
  notes?: Note[];
  transcript?: string;
  transcriptSegments?: TranscriptSegment[];
  durationSeconds?: number;
  status?: SessionStatus;
  aiSummary?: AiSummary;
}
