-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 20250509000000_init
-- Description: Initial schema — sessions, session_status enum, ai_summaries
--
-- This migration is hand-written to exactly match what `prisma migrate dev`
-- would generate from apps/api/prisma/schema.prisma.
--
-- Tables created:
--   sessions     — core session records with JSON notes storage
--   ai_summaries — Claude-generated summaries, one-to-one with sessions
--
-- Design notes carried forward from schema.prisma:
--   - sessions.notes is JSONB (not JSON) for Postgres — allows GIN indexing
--     in future if note content search is added.
--   - sessions.user_uuid is NOT a foreign key — UUID-only identity model
--     means there is no users table to reference.
--   - ai_summaries has ON DELETE CASCADE so deleting a session also removes
--     its summary without a separate application-level delete.
-- ─────────────────────────────────────────────────────────────────────────────

-- Create the session_status enum type.
-- Prisma maps this from the SessionStatus enum in schema.prisma.
-- The @map("session_status") directive sets the Postgres type name.
CREATE TYPE "session_status" AS ENUM (
  'IDLE',
  'RECORDING',
  'STOPPED',
  'SUMMARISED'
);

-- Create the sessions table.
-- @map("sessions") sets the Postgres table name.
CREATE TABLE "sessions" (
  -- UUID v4 primary key. Generated by the client before recording starts.
  "id"              UUID          NOT NULL,

  -- Owner UUID. Indexed below. No FK — no users table.
  "user_uuid"       UUID          NOT NULL,

  -- Session title. Empty string default matches @default("") in schema.
  "title"           TEXT          NOT NULL DEFAULT '',

  -- Notes stored as JSONB array. Default empty array.
  -- JSONB over JSON: binary storage, faster reads, allows future GIN indexing.
  "notes"           JSONB         NOT NULL DEFAULT '[]',

  -- Full raw transcript concatenated from AssemblyAI FinalTranscript events.
  "transcript"      TEXT          NOT NULL DEFAULT '',

  -- Recording duration set when status transitions to STOPPED.
  "duration_seconds" INTEGER      NOT NULL DEFAULT 0,

  -- Session lifecycle state.
  "status"          "session_status" NOT NULL DEFAULT 'IDLE',

  -- Prisma-managed timestamps.
  "created_at"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"      TIMESTAMP(3) NOT NULL,

  CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- Index for fast lookup of all sessions belonging to a user.
-- Used by GET /api/sessions which filters by user_uuid.
CREATE INDEX "sessions_user_uuid_idx"
  ON "sessions"("user_uuid");

-- Compound index for user sessions ordered by last updated — drives the
-- sidebar session list which sorts by updatedAt DESC.
CREATE INDEX "sessions_user_uuid_updated_at_idx"
  ON "sessions"("user_uuid", "updated_at" DESC);

-- Create the ai_summaries table.
-- One-to-one with sessions. Nullable from the session side (aiSummary?).
-- @map("ai_summaries") sets the Postgres table name.
CREATE TABLE "ai_summaries" (
  -- UUID v4 primary key. Generated by the API when summary is created.
  "id"            UUID          NOT NULL,

  -- Foreign key to sessions. UNIQUE enforces one-to-one relationship.
  "session_id"    UUID          NOT NULL,

  -- Overview paragraph from Claude.
  "overview"      TEXT          NOT NULL,

  -- JSON arrays of strings produced by Claude's structured output.
  "decisions"     JSONB         NOT NULL DEFAULT '[]',
  "action_items"  JSONB         NOT NULL DEFAULT '[]',
  "insights"      JSONB         NOT NULL DEFAULT '[]',

  -- The Claude model used — stored for auditing and reproducibility.
  "model_used"    TEXT          NOT NULL,

  "created_at"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "ai_summaries_pkey" PRIMARY KEY ("id")
);

-- Unique index on session_id enforces the one-to-one constraint from the
-- ai_summaries side (Prisma uses this for @unique on sessionId).
CREATE UNIQUE INDEX "ai_summaries_session_id_key"
  ON "ai_summaries"("session_id");

-- Foreign key constraint with CASCADE delete.
-- Deleting a session removes its summary automatically.
-- Prisma generates this from: session Session @relation(..., onDelete: Cascade)
ALTER TABLE "ai_summaries"
  ADD CONSTRAINT "ai_summaries_session_id_fkey"
  FOREIGN KEY ("session_id")
  REFERENCES "sessions"("id")
  ON DELETE CASCADE
  ON UPDATE CASCADE;
